version: "3.9"
services:
  nginx:
    image: rgolea/baneverywhere-proxy:latest
    container_name: baneverywhere-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/

  api:
    image: rgolea/baneverywhere:latest
    command: node apps/api/main.js
    container_name: api-baneverywhere
    stdin_open: true
    tty: true
    restart: unless-stopped
    expose:
      - 3333
    env_file: /.env
    depends_on:
      - postgres
      - redis

  bot:
    image: rgolea/baneverywhere:latest
    command: node apps/bot/main.js
    container_name: bot-baneverywhere
    stdin_open: true
    tty: true
    restart: unless-stopped
    env_file: /.env
    depends_on:
      - redis

  bot-handler:
    image: rgolea/baneverywhere:latest
    command: node apps/bot-handler/main.js
    container_name: bot-handler-baneverywhere
    stdin_open: true
    tty: true
    restart: unless-stopped
    env_file: /.env
    depends_on:
      - redis
      - postgres

  online-checker:
    image: rgolea/baneverywhere:latest
    command: node apps/online-checker/main.js
    container_name: online-checker-baneverywhere
    stdin_open: true
    tty: true
    restart: unless-stopped
    env_file: /.env
    depends_on:
      - redis
      - postgres

  queue-processor:
    image: rgolea/baneverywhere:latest
    command: node apps/queue-processor/main.js
    container_name: queue-processor-baneverywhere
    stdin_open: true
    tty: true
    restart: unless-stopped
    env_file: /.env
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:10
    container_name: postgres-baneverywhere
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=baneverywhere
    expose:
      - 5432
    volumes:
      - /data/postgresql/:/var/lib/postgresql/
    depends_on:
      - redis
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.2.6
    container_name: redis-baneverywhere
    restart: unless-stopped
    command: redis-server
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
