name: Deploy to Production
on:
  push:
    branches:
      - master
env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  NX_BRANCH: ${{ github.ref }}
  NX_RUN_GROUP: $${{ github.run_id }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache node modules
        uses: actions/cache@v2
        id: npm-cache
        with:
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          path: |
            **/node_modules
            /tmp/.buildx-cache-api
            /tmp/.buildx-cache-proxy
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'master'
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.13
      - run: git fetch origin master
      - run: npm ci
      - run: npm run generate
      - run: npx nx-cloud start-ci-run
      - run: npx nx run-many --target=build --all --configuration=production --parallel --max-parallel=2
      - run: npx nx-cloud stop-all-agents
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: rgolea
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push API Image
        id: docker_build_api
        uses: docker/build-push-action@v2
        with:
          file: ./config/docker/api.Dockerfile
          push: true
          tags: rgolea/baneverywhere:latest
          context: .
          cache-from: type=local,src=/tmp/.buildx-cache-api
          cache-to: type=local,dest=/tmp/.buildx-cache-api-new,mode=max
      - name: Build and push API Image
        id: docker_build_proxy
        uses: docker/build-push-action@v2
        with:
          file: ./config/docker/nginx.Dockerfile
          push: true
          tags: rgolea/baneverywhere-proxy:latest
          context: .
          cache-from: type=local,src=/tmp/.buildx-cache-proxy
          cache-to: type=local,dest=/tmp/.buildx-cache-proxy-new,mode=max
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-api
          rm -rf /tmp/.buildx-cache-proxy
          mv /tmp/.buildx-cache-api-new /tmp/.buildx-cache-api
          mv /tmp/.buildx-cache-proxy-new /tmp/.buildx-cache-proxy
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /app
            docker-compose down
            rm -rf docker-compose.yml
            wget https://raw.githubusercontent.com/rgolea/baneverywhere/master/docker-compose.yml --no-cache --no-dns-cache
            docker-compose up -d
            docker system prune -af


  agents:
    runs-on: ubuntu-latest
    name: Nx Agent ${{ matrix.agent }}
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [ 1, 2, 3 ]
    steps:
      - name: Cache node modules
        uses: actions/cache@v2
        id: npm-cache
        with:
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          path: |
            **/node_modules
          restore-keys: |
            ${{ runner.os }}-npm-
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.13
      - run: npm ci
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent


